[package]
name = "real-world-game-maps"
version = "0.0.1"
authors = ["Thomas Rupprecht <rupprecht.thomas@gmail.com>"]
edition = "2018"
description = "Create game-maps from real world data"
license = "MIT"

[dependencies]
bincode = "1.3.1"
nom = "6.0.1"
serde = "1.0.119"
tiff = "0.6.1"
